### ISSUE TITLE
Gives FileNotFoundError

### ISSUE THREAD

**Issue by nagracks** [topisani/Discurses#16]
```bash
$ discurses
```
Gives this error
```
Traceback (most recent call last):
  File "/usr/bin/discurses", line 11, in <module>
    load_entry_point('discurses==0.2.4', 'console_scripts', 'discurses')()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.5/site-packages/discurses/__init__.py", line 1, in <module>
    import discurses.discord
  File "/usr/lib/python3.5/site-packages/discurses/discord.py", line 10, in <module>
    import discurses.config as config
  File "/usr/lib/python3.5/site-packages/discurses/config.py", line 10, in <module>
    with open(CONFIG_FILE_PATH, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/nagra/.config/discurses.yaml'
```

**Comment by topisani** [comment]
https://github.com/topisani/Discurses#authentication
That should help
