### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by xSynthx** [topisani/Discurses#22]
When I added my token to the file, I did the rename and everything and I put the file into `~/.config/` I put it in that folder, not any other folder. I am on mac, and all it says when I type `discurses` into terminal, is: "Logging in... Hang tight!"
I found the log file, and this is what it contained:
```
18-08-2017 19:29:39 [INFO] discurses: Now logging!
18-08-2017 19:29:39 [INFO] discurses: Now logging!
18-08-2017 19:29:39 [WARNING] discord.client: PyNaCl is not installed, voice will NOT be supported
18-08-2017 19:29:39 [WARNING] discord.client: PyNaCl is not installed, voice will NOT be supported
18-08-2017 19:29:39 [INFO] discord.client: logging in using static token
18-08-2017 19:29:39 [INFO] discord.client: logging in using static token
18-08-2017 19:29:40 [INFO] discord.gateway: Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6
18-08-2017 19:29:40 [INFO] discord.gateway: Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6
18-08-2017 19:29:40 [INFO] discord.gateway: sent the identify payload to create the websocket
18-08-2017 19:29:40 [INFO] discord.gateway: sent the identify payload to create the websocket
18-08-2017 19:29:43 [ERROR] asyncio: Task exception was never retrieved
future: <Task finished coro=<ConnectionState._delay_ready() done, defined at /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/discord/state.py:166> exception=AttributeError('_member_count',)>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/discord/state.py", line 180, in _delay_ready
    chunks.extend(self.chunks_needed(server))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/discord/state.py", line 163, in chunks_needed
    for chunk in range(math.ceil(server._member_count / 1000)):
AttributeError: _member_count
18-08-2017 19:29:54 [DEBUG] discurses.discord: Running 0 event handlers for on_message
18-08-2017 19:29:54 [DEBUG] discurses.discord: Running 0 event handlers for on_message
18-08-2017 19:29:57 [DEBUG] discurses.ui.main: Keypres reached global map: ('mouse press', 1.0, 71, 11)
18-08-2017 19:29:57 [DEBUG] discurses.ui.main: Keypres reached global map: ('mouse press', 1.0, 71, 11)
18-08-2017 19:29:57 [DEBUG] discurses.ui.main: Keypres reached global map: ('mouse release', 0, 71, 11)
18-08-2017 19:29:57 [DEBUG] discurses.ui.main: Keypres reached global map: ('mouse release', 0, 71, 11)
18-08-2017 19:30:02 [DEBUG] discurses.discord: Running 0 event handlers for on_message
18-08-2017 19:30:02 [DEBUG] discurses.discord: Running 0 event handlers for on_message
```

**Comment by xSynthx** [comment]
Anyone got a solution?

**Comment by Ge0** [comment]
Do you still have the same issue with the upstream version?
