### ISSUE TITLE
List index out of range after loading server list

### ISSUE THREAD

**Issue by parkerlreed** [topisani/Discurses#23]
Arch x86_64
discurses from pip

I'm in 27 servers if that makes a difference.

````
Traceback (most recent call last):        │+ /r/Android: 17                                                                                                              │
  File "/usr/lib/python3.6/site-packages/discord/client.py", line 307, in _run_event                                                                                     │
    yield from getattr(self, event)(*args, **kwargs)lehome: 4                                                                                                            │
  File "/usr/lib/python3.6/site-packages/discurses/discord.py", line 36, in eh                                                                                           │
    f(*args, **kwargs)                    │+ Discord Electronics Server: 16                                                                                              │
  File "/usr/lib/python3.6/site-packages/discurses/ui/message_list.py", line 42, in _on_message                                                                          │
    if message.timestamp.date() != self.list_walker[-1].message.timestamp.date():                                                                                        │
IndexError: list index out of range       │+ Facepunch CD/TG/A: 21                            
````

**Comment by topisani** [comment]
Sorry, but I dont really have time to update this project anymore. If someone wants to take over, that would be awesome!

**Comment by Ge0** [comment]
I have submitted a PR. This is a dirty hack but I guess that it temporarily solves the issue.

**Comment by topisani** [comment]
#24 merged, should close this
