### ISSUE TITLE
Unable to properly run Discurses

### ISSUE THREAD

**Issue by DailytheNoob** [topisani/Discurses#39]
Hello,
Installed according to the Readme on my RasPi B+, but when I try running it it returns the following:
```
Traceback (most recent call last):
  File "/usr/local/bin/discurses", line 9, in <module>
    load_entry_point('discurses==0.3.0', 'console_scripts', 'discurses')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/local/lib/python3.4/dist-packages/discurses/__init__.py", line 1, in <module>
    from . import discord
  File "/usr/local/lib/python3.4/dist-packages/discurses/discord.py", line 32
    async def eh(*args, **kwargs):
            ^
SyntaxError: invalid syntax
```

Can you help?

**Comment by topisani** [comment]
You need python 3.5 i think. Make sure to install it with `pip3` if thats what the python 3 binary is called on your distro (i suspect it is)
