### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by warshanks** [topisani/Discurses#40]
Traceback (most recent call last):
  File "/usr/local/bin/discurses", line 7, in <module>
    from discurses import main
  File "/usr/local/lib/python3.5/dist-packages/discurses/__init__.py", line 1, in <module>
    from . import discord
  File "/usr/local/lib/python3.5/dist-packages/discurses/discord.py", line 10, in <module>
    import discurses.ui as ui
  File "/usr/local/lib/python3.5/dist-packages/discurses/ui/__init__.py", line 10, in <module>
    from discurses.ui.chat import ChatWindow
  File "/usr/local/lib/python3.5/dist-packages/discurses/ui/chat.py", line 15, in <module>
    class ChatWindow(urwid.WidgetWrap, HasModal):
  File "/usr/local/lib/python3.5/dist-packages/discurses/ui/chat.py", line 24, in ChatWindow
    class FocusTarget(enum.Enum):
  File "/usr/local/lib/python3.5/dist-packages/discurses/ui/chat.py", line 25, in FocusTarget
    CHANNEL_SELECTOR = enum.auto()
AttributeError: module 'enum' has no attribute 'auto'

I checked my PATH and installed the latest version of Python to no avail.

**Comment by Ge0** [comment]
Are you actually sure to use Python >= 3.5?

**Comment by warshanks** [comment]
Yeah, I'm on Python 3.6.5.

**Comment by Ge0** [comment]
Your path shows that you are actually using Python 3.5.x. There is something wrong for sure.

This is not supported in Python 3.5. It's a mistake from me.

Anyway I have modified the install script since, now discurses has to be run on Python 3.6.x.

I suggest you install discurses in a virtualenvironment using python 3.6.

**Comment by warshanks** [comment]
Potentially dumb question but how do I uninstall my old discurses? I was going to reinstall it to fix the error but when i do pip3 uninstall discurses it gives me "Skipping discurses as it is not installed"

**Comment by warshanks** [comment]
So I tried to reinstall and I got this 

pip3.6 install discurses
Collecting discurses
  Using cached discurses-0.3.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-swwsrz2u/discurses/setup.py", line 5, in <module>
        from pip.req import parse_requirements
    ModuleNotFoundError: No module named 'pip.req'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-swwsrz2u/discurses/
