### ISSUE TITLE
TypeError: '<' not supported between instances of 'NoneType' and 'str'

### ISSUE THREAD

**Issue by KaKi87** [topisani/Discurses#50]
Hi,

Here is my configuration :
 - Discurses 0.3.3 (latest)
 - Debian 9.4 Stretch (latest)
 - Python 3.6.5 (latest)
 - Pip 10.0.1 (latest)
 - Discord token saved in `/root/.config/discurses.yaml`

But it doesn't work.

```
gnoring exception in on_ready                                                                                                               
Traceback (most recent call last):                                                                                                          
  File "/root/.pyenv/versions/3.6.5/lib/python3.6/site-packages/discord/client.py", line 307, in _run_event                                 
    yield from getattr(self, event)(*args, **kwargs)                                                                                        
  File "/root/.pyenv/versions/3.6.5/lib/python3.6/site-packages/discurses/discord.py", line 52, in on_ready                                 
    self.ui.on_ready()                                                                                                                      
  File "/root/.pyenv/versions/3.6.5/lib/python3.6/site-packages/discurses/ui/main.py", line 152, in on_ready                                
    self.set_tab(0)                                                                                                                         
  File "/root/.pyenv/versions/3.6.5/lib/python3.6/site-packages/discurses/ui/main.py", line 137, in set_tab                                 
    self.discord, [], None, name=str(tab + 1)))                                                                                             
  File "/root/.pyenv/versions/3.6.5/lib/python3.6/site-packages/discurses/ui/chat.py", line 46, in __init__                                 
    self.w_server_tree = ServerTree(self)                                                                                                   
  File "/root/.pyenv/versions/3.6.5/lib/python3.6/site-packages/discurses/ui/server_tree.py", line 15, in __init__                          
    key=lambda s: s.name):                                                                                                                  
TypeError: '<' not supported between instances of 'NoneType' and 'str'                                                                      
```

![sans titre 3](https://user-images.githubusercontent.com/21284089/40615668-fb2d93b0-6287-11e8-9f49-e4818abd265d.png)

Could you help me please ?

Thanks !

**Comment by AnonGuy** [comment]
I am having the same issue.
* Discurses 0.3.3 (latest)
* Arch Linux
* Python 3.6.5 (latest)
* Pip 10.0.1 (latest)

**Comment by AnonGuy** [comment]
Also using a pyenv installation of Python 3.6.5

**Comment by magistau** [comment]
Have the same
- Discurses 0.3.5
- Linux Mint 19.1
- Python 3.6.5
- Pip 9.0.1
