### ISSUE TITLE
FileNotFoundError on run

### ISSUE THREAD

**Issue by piqle** [topisani/Discurses#61]
When attempting to start discurses for a first time, I receive this error:

`
Traceback (most recent call last):
  File "/usr/bin/discurses", line 7, in <module>
    from discurses.__main__ import main
  File "/usr/lib/python3.6/site-packages/discurses/__main__.py", line 1, in <module>
    from . import discord
  File "/usr/lib/python3.6/site-packages/discurses/discord.py", line 9, in <module>
    import discurses.config as config
  File "/usr/lib/python3.6/site-packages/discurses/config.py", line 10, in <module>
    with open(CONFIG_FILE_PATH, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/piqle/.config/discurses.yaml'
`

This is a fresh Manjaro i3 install.

**Comment by piqle** [comment]
I didn't read the README completely. My fault.

Thanks!
